- name: Verify variables are set
  assert:
    that: "{{ item }} is defined"
    msg: Run erp_get_build role first
  with_items:
    - erp_debian_installer_environment
    - erp_build_number
    - erp_image_paths['kernel']
    - erp_image_paths['initrd']

- name: Set image
  set_fact:
    image_name: "debian-installer {{erp_debian_installer_environment}} build {{erp_build_number}}"

- name: Upload Kernel image
  mr_provisioner_image:
    description: "{{image_name}}"
    type: Kernel
    path: "{{erp_image_paths['kernel']}}"
    url: "{{cambridge_provisioner_url}}"
    token: "{{cambridge_provisioner_token}}"
  run_once: true
  register: kernel_image
- debug: var=kernel_image
- name: Upload Initrd image
  mr_provisioner_image:
    description: "{{image_name}}"
    type: Initrd
    path: "{{erp_image_paths['initrd']}}"
    url: "{{cambridge_provisioner_url}}"
    token: "{{cambridge_provisioner_token}}"
  run_once: true
  register: initrd_image
- debug: var=initrd_image

- name: Provision machine
  mr_provisioner_machine_provision:
    machine_name: "{{inventory_hostname}}"
    image_description: "{{image_name}}"
    preseed_name: danrue/erp-17.08-debian-20170727.567664d4
    url: "{{cambridge_provisioner_url}}"
    token: "{{cambridge_provisioner_token}}"
  register: provision_machine
- debug: var=provision_machine

# TODO: Wait for machine to become available
