- name: Verify variables are set
  assert:
    that: "{{ item }} is defined"
    msg: Run erp_get_build role first
  with_items:
    - erp_debian_installer_environment
    - erp_build_number
    - erp_image_paths['kernel']
    - erp_image_paths['initrd']

- name: Set image
  set_fact:
    image_name: "debian-installer {{erp_debian_installer_environment}} build {{erp_build_number}}"

- name: Upload Kernel image
  mr_provisioner_image:
    description: "{{image_name}}"
    type: Kernel
    path: "{{erp_image_paths['kernel']}}"
    url: "{{cambridge_provisioner_url}}"
    token: "{{cambridge_provisioner_token}}"
  register: kernel_image
- debug: var=kernel_image
- name: Upload Initrd image
  mr_provisioner_image:
    description: "{{image_name}}"
    type: Initrd
    path: "{{erp_image_paths['initrd']}}"
    url: "{{cambridge_provisioner_url}}"
    token: "{{cambridge_provisioner_token}}"
  register: initrd_image
- debug: var=initrd_image


- fail: msg="Asdf"

# TODO: Replace with API call, once supported.
- name: Edit Machines
  pause:
    prompt: "In Mr. Provisioner, modify each machine in your host group to {{erp_build_number}}. <enter> once complete"

# TODO: Replace with API call, once supported.
- name: Reboot machines and install OS
  pause:
    prompt: "In Mr. Provisioner, PXE Reboot each machine to install new OS. <enter> once complete"
